project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Yumeri Ninomiya"  # ← ここがサイト上部の "web" を "Name" に変える
  navbar: 
    background: light
    collapse-below: xl 
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching
  page-footer:
      background: "#9ED48A"
      left: "© 2026 Name"  
      right:
        - icon: envelope
          href: mailto:your@email.com  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

navbar:
  right:
    - icon: github
      # href: https://github.com/yume0002
      href: https://github.com/yumeri-ninomiya-page/yumeri-ninomiya-page.github.io/