project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Yumeri Ninomiya"  # ← ここがサイト上部の "web" を "Name" に変える
  navbar: 
    background: light
    collapse-below: xl 
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching
  page-footer:
      background: "#D7E6AC"
      right: "© 2026 Yumeri Ninomiya"  
      left:  "<i class='bi bi-envelope'></i> 233e126e[at]stu.kobe-u.jp" 

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

navbar:
  right:
    - icon: github
      # href: https://github.com/yume0002
      href: https://github.com/yumeri-ninomiya-page/yumeri-ninomiya-page.github.io/